# Stage 1: Build stage
FROM ubuntu:22.04

# Update package repositories and install x11-apps
RUN apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y x11-apps && \
    rm -rf /var/lib/apt/lists/*

# Set the entrypoint for the image
ENTRYPOINT ["xeyes"]
